### ISSUE TITLE
precourse deliverables

### ISSUE THREAD

**Issue by abriyusif** [DeNepo/precourse#5]
1. [x] Create this issue
2. [x] Install softwares
3. [x] Install VSCode extensions
4. [ ] Organize your computer
5. [ ] GitHub setup
6. [ ] Fork and Clone the flashcards repository
7. [ ] Prep work for Workflows Chapter 1

**Comment by colevandersWands** [comment]
@abriyusif , you should make your precourse issue in [your class repo](https://github.com/iTalantaAcademy-kakuma-1/home) and move it to the deliverables board. then you classmates and coaches will be able to find your work and help you
