### ISSUE TITLE
Precourse Deliverables

### ISSUE THREAD

**Issue by Ohisa-Franco** [DeNepo/precourse#6]
1. [x] Create this issue
2. [x] Install software
3. [x] Install VSCode extensions
4. [x] Organize your computer
5. [x] GitHub setup
6. [ ] Fork and Clone the flashcards repository
7. [ ] Prep work for Workflows Chapter 1

**Comment by colevandersWands** [comment]
@franco9535  , you should make your precourse issue in [your class repo](https://github.com/iTalantaAcademy-kakuma-1/home) and move it to the deliverables board. then you classmates and coaches will be able to find your work and help you
